### ISSUE TITLE
XLSX to HTML conversion fails

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/reports#105]
### Environment

- Platform version: 6.10-SNAPSHOT
- Windows 7

### Description of the bug or enhancement

- Import sample-library app
- Import the report attached (or create any report with XLSX template and alterable output)
- Run the report with HTML output

ER:
Report file in HTML

AR:
```
java_remote_bridge com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge@2c24aa30 is disposed

com.haulmont.cuba.core.global.RemoteException:
---
java.lang.RuntimeException: com.haulmont.yarg.exception.ReportingException: An error occurred while running task in Open Office server
---
com.haulmont.yarg.exception.ReportingException: An error occurred while running task in Open Office server
---
com.sun.star.lang.DisposedException: java_remote_bridge com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge@2c24aa30 is disposed
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy261.createReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy60.createReport(Unknown Source)
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:269)
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:366)
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:361)
	at com.haulmont.cuba.gui.backgroundwork.LocalizedTaskWrapper.run(LocalizedTaskWrapper.java:54)
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.call(WebBackgroundWorker.java:205)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:376)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

[Book availability in department (1).zip](https://github.com/cuba-platform/reports/files/2414761/Book.availability.in.department.1.zip)

**Comment by andreysubbotin** [comment]
Problem with LibreOffice. Try to print report again. Not a bug.
