### ISSUE TITLE
NPE while create report with Wizard

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#120]
### Environment

- Platform version: 7.0
### Description of the bug or enhancement
- Minimal reproducible example
   - Navigates to Reports
   - Try to click "Create -> New" or "Create -> Using wizard"
- Actual behavior
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadDatasource(FieldGroupLoader.java:283)
	at com.haulmont.cuba.gui.xml.layout.loaders.FieldGroupLoader.loadComponent(FieldGroupLoader.java:101)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:52)
```

**Comment by jreznot** [comment]
Current exception:
```
java.lang.NullPointerException
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractTableLoader.loadComponent(AbstractTableLoader.java:155)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:52)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.FragmentLoader.loadComponent(FragmentLoader.java:147)
	at com.haulmont.cuba.gui.xml.layout.loaders.FragmentComponentLoader.loadComponent(FragmentComponentLoader.java:253)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.AbstractBoxLoader.loadComponent(AbstractBoxLoader.java:52)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponents(ContainerLoader.java:38)
	at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:90)
	at com.haulmont.cuba.gui.xml.layout.loaders.WindowLoader.loadComponent(WindowLoader.java:99)
	at com.haulmont.cuba.web.sys.WebScreens.loadWindowFromXml(WebScreens.java:324)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:202)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:972)
	at com.haulmont.cuba.gui.components.HasWindowManager.openWindow(HasWindowManager.java:75)
	at com.haulmont.reports.gui.report.browse.ReportBrowser$3.actionPerform(ReportBrowser.java:173)
	at com.haulmont.cuba.web.gui.components.WebPopupButton.lambda$setPopupButtonAction$1(WebPopupButton.java:329)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by jreznot** [comment]
Fixed in https://github.com/cuba-platform/cuba/issues/1521
