### ISSUE TITLE
Show Charts screen always runs report with default template

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/reports#121]
https://www.cuba-platform.com/discuss/t/error-occur-while-generating-reports/6622

### Environment

- Platform version: 6.9.0

### Description of the bug or enhancement

- Minimal reproducible example

Sample project: [sampleProject - Copy.zip](https://github.com/cuba-platform/reports/files/2565929/sampleProject.-.Copy.zip)

1. Create report with 2 templates: XLSX (DEFAULT), Chart
2. Prepare data sets and save report
3. Open Show Charts screen
4. Run report

- Actual behavior

Exception is thrown:
```
java.lang.IllegalStateException: Unable to parse JSON chart configuration
	at com.haulmont.charts.web.toolkit.ui.amcharts.CubaAmchartsScene.setJson(CubaAmchartsScene.java:147)
	at com.haulmont.charts.web.gui.components.charts.amcharts.WebCustomChart.setNativeJson(WebCustomChart.java:65)
	at com.haulmont.charts.web.ui.JsonChartController.init(JsonChartController.java:28)
	at com.haulmont.cuba.gui.xml.layout.loaders.FrameLoader$FrameLoaderInitTask.execute(FrameLoader.java:271)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext$InitTaskExecutor.run(ComponentLoaderContext.java:266)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext.executeInitTasks(ComponentLoaderContext.java:160)
	at com.haulmont.cuba.gui.WindowManager.openFrame(WindowManager.java:1014)
	at com.haulmont.cuba.gui.WindowManager.openFrame(WindowManager.java:964)
	at com.haulmont.cuba.gui.components.WindowDelegate.openFrame(WindowDelegate.java:307)
	at com.haulmont.cuba.web.gui.WebWindow.openFrame(WebWindow.java:534)
	at com.haulmont.cuba.gui.components.AbstractFrame.openFrame(AbstractFrame.java:569)
	at com.haulmont.reports.gui.report.run.ShowChartController.openChart(ShowChartController.java:115)
	at com.haulmont.reports.gui.report.run.ShowChartController.printReport(ShowChartController.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Forum topic: https://www.cuba-platform.com/discuss/t/illegalstateexception-unable-to-parse-json-chart-configuration/7076

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[807afb85](https://git.haulmont.com/platform/reports/commit/807afb85bb1fc608b94d3644cf2198074dd112ee) in **release_6_10** - Show Charts screen always runs report with default template#121

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[8d325cee](https://git.haulmont.com/platform/reports/commit/8d325cee0c31b66e8a246d562a4db0baeef150b6) in **master** - Show Charts screen always runs report with default template#121
