### ISSUE TITLE
Unfetched attribute exception when included to @NamePattern field is not added to band

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#123]
#### Environment

- Platform version: 6.9, 6.10, 7.0
#### Description of the bug or enhancement

1. Using wizard create a report for the "User" entity
2. For the selected attributes do not add the name field
3.  Create a table template for the report
4. Open Show Tables screen, run the report

```
com.haulmont.reports.exception.ReportingException: Cannot fetch instance name for entity class com.haulmont.cuba.security.entity.User. Please add all attributes used at instance name to report configuration. Report name [Report for entity "User"]
Error getting instance name
null
Cannot get unfetched attribute [name] from detached object com.haulmont.cuba.security.entity.User-60885987-1b61-4247-94c7-dff348347f93 [detached].
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:341)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:284)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:202)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[7d890f31](https://git.haulmont.com/platform/reports/commit/7d890f31b93f18eed630f4d20b2f8280ff8b099d) in **release_6_10** - Unfetched attribute exception when included to @NamePattern field is not added to band #123

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[33c1105e](https://git.haulmont.com/platform/reports/commit/33c1105e539743f624e806a5c86078201fd6d68a) in **master** - Unfetched attribute exception when included to @NamePattern field is not added to band #123
