### ISSUE TITLE
Report generation hangs if using DOCX -> PDF/HTML conversion without LibreOffice installed

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/reports#134]
### Environment

- Platform version: 7.0
- Operating system: Windows

### Description of the bug or enhancement

1) OpenOffice/LibreOffice is not installed on the PC
2) ``` reporting.openoffice.docx.useOfficeForDocumentConversion=true```
3) Create the report with DOCX template and PDF output type
4) Launch the report

AR:

Report generation hangs

![108.JPG](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/37a38185-6f71-4f3a-97c5-5abe4aa8f35b)

Logs:

```
2018-12-03 12:43:37.888 WARN  [BackgroundTask-0-admin/app-core/admin] com.haulmont.yarg.formatters.impl.xls.DocumentConverterImpl - An error occurred while converting. System will retry to generate report again.
com.haulmont.yarg.exception.OpenOfficeException: Unable to create Open office components.
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:78) ~[yarg-2.1.2.jar:na]
	at com.haulmont.reports.libintegration.CubaOfficeIntegration.lambda$null$0(CubaOfficeIntegration.java:34) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContext.withSecurityContext(AppContext.java:179) ~[cuba-global-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.libintegration.CubaOfficeIntegration.lambda$runTaskWithTimeout$1(CubaOfficeIntegration.java:33) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: no office executable found!
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapConnector.connect(BootstrapConnector.java:130) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapSocketConnector.connect(BootstrapSocketConnector.java:47) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:60) ~[yarg-2.1.2.jar:na]
	... 7 common frames omitted
Caused by: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: no office executable found!
	at com.haulmont.yarg.formatters.impl.doc.connector.OOServer.start(OOServer.java:103) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapConnector.connect(BootstrapConnector.java:103) ~[yarg-2.1.2.jar:na]
	... 9 common frames omitted
2018-12-03 12:43:38.904 INFO  [BackgroundTask-0-admin/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - An error occurred while running report [Report for entity "User" DOCX-PDF] with parameters [
entity:com.haulmont.cuba.security.entity.User-a405db59-e674-4f63-8afe-269dda788fe8 [detached]].
2018-12-03 12:43:38.925 INFO  [BackgroundTask-0-admin/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - Trace: 
com.haulmont.yarg.exception.OpenOfficeException: Unable to create Open office components.
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:78) ~[yarg-2.1.2.jar:na]
	at com.haulmont.reports.libintegration.CubaOfficeIntegration.lambda$null$0(CubaOfficeIntegration.java:34) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.core.sys.AppContext.withSecurityContext(AppContext.java:179) ~[cuba-global-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.libintegration.CubaOfficeIntegration.lambda$runTaskWithTimeout$1(CubaOfficeIntegration.java:33) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: no office executable found!
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapConnector.connect(BootstrapConnector.java:130) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapSocketConnector.connect(BootstrapSocketConnector.java:47) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.OfficeConnection.open(OfficeConnection.java:60) ~[yarg-2.1.2.jar:na]
	... 7 common frames omitted
Caused by: com.haulmont.yarg.formatters.impl.doc.connector.BootstrapException: no office executable found!
	at com.haulmont.yarg.formatters.impl.doc.connector.OOServer.start(OOServer.java:103) ~[yarg-2.1.2.jar:na]
	at com.haulmont.yarg.formatters.impl.doc.connector.BootstrapConnector.connect(BootstrapConnector.java:103) ~[yarg-2.1.2.jar:na]
	... 9 common frames omitted
2018-12-03 12:43:38.927 DEBUG [BackgroundTask-0-admin/app-core/admin] com.haulmont.cuba.core.app.execution.ExecutionsImpl - End execution context: group=Reporting, key=f6398e6f-bcd1-3fcd-5a82-2f95c3d7e0c9
2018-12-03 12:43:38.934 ERROR [BackgroundTask-0-admin/app-core/admin] com.haulmont.cuba.core.sys.ServiceInterceptor - Exception: 
com.haulmont.reports.exception.FailedToConnectToOpenOfficeException: Unable to create Open office components. Report name [Report for entity "User" DOCX-PDF]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:337) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:302) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:196) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35) ~[reports-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117) ~[cuba-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy258.createReport(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) [cuba-core-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.sun.proxy.$Proxy62.createReport(Unknown Source) [na:na]
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:266) [reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:386) [reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:381) [reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.backgroundwork.LocalizedTaskWrapper.run(LocalizedTaskWrapper.java:55) [cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.call(WebBackgroundWorker.java:205) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:376) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
2018-12-03 12:43:38.957 DEBUG [BackgroundTask-0-admin/app/admin] com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker - Done task. User: admin
2018-12-03 12:43:38.967 DEBUG [BackgroundTask-0-admin/app/admin] com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker - Exception in background task
java.util.concurrent.ExecutionException: com.haulmont.reports.exception.FailedToConnectToOpenOfficeException: Unable to create Open office components. Report name [Report for entity "User" DOCX-PDF]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_171]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.handleDone(WebBackgroundWorker.java:278) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.lambda$done$0(WebBackgroundWorker.java:187) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1468) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.ui.UI$3.run(UI.java:1532) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2018) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1007) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1983) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1949) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1406) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.vaadin.ui.UI.access(UI.java:1529) ~[vaadin-server-8.6.1-2-cuba.jar:8.6.1-2-cuba]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor$1.done(WebBackgroundWorker.java:186) [cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) ~[na:1.8.0_171]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:376) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: com.haulmont.reports.exception.FailedToConnectToOpenOfficeException: Unable to create Open office components. Report name [Report for entity "User" DOCX-PDF]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:337) ~[na:na]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:302) ~[na:na]
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:196) ~[na:na]
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy258.createReport(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) ~[na:na]
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.sun.proxy.$Proxy62.createReport(Unknown Source) ~[na:na]
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:266) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:386) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:381) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.backgroundwork.LocalizedTaskWrapper.run(LocalizedTaskWrapper.java:55) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.call(WebBackgroundWorker.java:205) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	... 4 common frames omitted
2018-12-03 12:43:38.974 ERROR [BackgroundTask-0-admin/app/admin] com.haulmont.cuba.gui.executors.BackgroundWorker - Exception occurred in background task
com.haulmont.reports.exception.FailedToConnectToOpenOfficeException: Unable to create Open office components. Report name [Report for entity "User" DOCX-PDF]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:337) ~[na:na]
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:302) ~[na:na]
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:196) ~[na:na]
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy258.createReport(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94) ~[na:na]
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.sun.proxy.$Proxy62.createReport(Unknown Source) ~[na:na]
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:266) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:386) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.reports.gui.ReportGuiManager$1.run(ReportGuiManager.java:381) ~[reports-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.gui.backgroundwork.LocalizedTaskWrapper.run(LocalizedTaskWrapper.java:55) ~[cuba-gui-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.call(WebBackgroundWorker.java:205) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker$WebTaskExecutor.lambda$startExecution$1(WebBackgroundWorker.java:376) ~[cuba-web-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

**Comment by sukhova** [comment]
This issue is related to background tasks

1) Create the report for users with DOCX template and PDF output or use it from attachments
2) Go to the **Administration** -> **Application Properties**
3) ```reporting.useBackgroundReportProcessing = true```
4) Launch the report with count of users more then 30

[Report for entity _User_ cool.zip](https://github.com/cuba-platform/reports/files/2643993/Report.for.entity._User_.cool.zip)
[User.zip](https://github.com/cuba-platform/reports/files/2644019/User.zip)
