### ISSUE TITLE
Lack of validation for default report template in report editor

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/reports#144]
### Environment
- Platform version: 6.8 or later

### Description of the bug or enhancement
Launch refapp 6.8 or use any cubadev server.
Menu -> Reports -> Reports.
Create -> New.
Name = Test.
Add groovy dataset with default empty data.
Press Save -> report is saved successfully.

Press Run (in editor) -> Run report -> you get an unexpected exception:
```
com.haulmont.reports.exception.ReportingException: No default template specified for report [Test]
	at com.haulmont.reports.ReportingBean.getDefaultTemplate(ReportingBean.java:632)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:197)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Press "Save and close".
Press "Run" from browser -> you get the same unexpected exception.

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[601cbc45](https://git.haulmont.com/platform/reports/commit/601cbc45c8421233dd73ebb8ac3cab493c678b82) in **release_6_10** - Lack of validation for default report template in report editor #144

**Comment by haulmont-git** [comment]
Git changesets by `s.fedorov`: 

[12febbf4](https://git.haulmont.com/platform/reports/commit/12febbf4ef00c1a742bf0909bfb3e61d7fbbc4a4) in **release_6_10** - Lack of validation for default report template in report editor #144
