### ISSUE TITLE
ReportingException occurs when trying to run the report for the list of entities selected by query with empty parameter

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#157]
#### Environment

- Platform version: 6.8 - snapshot
Reporting

#### Description of the bug or enhancement

1. Create a report for the list of entities selected by query
2. Select string parameter 
3. Change the requirement of the parameter to false in Parameters and Formats tab
4. Set one of the predefined transformations
5. Save changes and try to run the report

```
com.haulmont.reports.exception.ReportingException: An error occurred while loading data for band [Cars] and query [Dataset]. Report name [Report for entity "Car"]
An error occurred while loading data for data set [Dataset]
An exception occurred while creating a query in EntityManager: 
Exception Description: Syntax error parsing [select
e.vin ,
model.name ,
model.numberOfSeats ,
colour.name from ref$Car e 
left join e.model model 
left join e.colour colour 
 where 1=1 ESCAPE '\']. 
[130, 146] The expression is not a valid conditional expression.

Exception Description: Syntax error parsing [select
e.vin ,
model.name ,
model.numberOfSeats ,
colour.name from ref$Car e 
left join e.model model 
left join e.colour colour 
 where 1=1 ESCAPE '\']. 
[130, 146] The expression is not a valid conditional expression.
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:341)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:284)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:188)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy327.createReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy74.createReport(Unknown Source)
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:264)
	at com.haulmont.reports.gui.ReportGuiManager.printReportSync(ReportGuiManager.java:235)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:206)
	at com.haulmont.reports.gui.report.run.InputParametersWindow.printReport(InputParametersWindow.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:92)
	at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:44)
```

**Comment by andreysubbotin** [comment]
Fixed in #182
