### ISSUE TITLE
UberJAR for CORE module can't start with Reporting

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/reports#168]
### Environment

- Platform version: 7.0.0
### Description of the bug or enhancement
- Minimal reproducible example
  - Create new project using CUBA Studio. Add Reporting module. 
  - Configure UberJAR deployment. Use multi-JAR (not single Uber JAR) configuration
  - Build UberJAR and start `java -jar app-core.jar`
- Actual behavior
Error while start: 
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1270) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:304) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.createDefaultStrategy(DispatcherServlet.java:900) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.getDefaultStrategies(DispatcherServlet.java:868) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.initHandlerAdapters(DispatcherServlet.java:657) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.initStrategies(DispatcherServlet.java:506) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.onRefresh(DispatcherServlet.java:494) ~[na:na]
        at org.springframework.web.servlet.FrameworkServlet.onApplicationEvent(FrameworkServlet.java:835) ~[na:na]
        at org.springframework.web.servlet.FrameworkServlet$ContextRefreshListener.onApplicationEvent(FrameworkServlet.java:1182) ~[na:na]
        at org.springframework.web.servlet.FrameworkServlet$ContextRefreshListener.onApplicationEvent(FrameworkServlet.java:1178) ~[na:na]
        at org.springframework.context.event.GenericApplicationListenerAdapter.onApplicationEvent(GenericApplicationListenerAdapter.java:64) ~[na:na]
        at org.springframework.context.event.SourceFilteringListener.onApplicationEventInternal(SourceFilteringListener.java:109) ~[na:na]
        at org.springframework.context.event.SourceFilteringListener.onApplicationEvent(SourceFilteringListener.java:73) ~[na:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[na:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[na:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[na:na]
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:696) ~[na:na]
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:662) ~[na:na]
        at com.haulmont.cuba.core.sys.remoting.RemotingServlet.initWebApplicationContext(RemotingServlet.java:95) ~[na:na]
```

**Comment by andreysubbotin** [comment]
https://github.com/cuba-platform/reports/commit/19306bc8e18dfa2d084ace5e39f852667339a713
