### ISSUE TITLE
Exception occurs when trying to set renderers for the pivot table report template

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#190]
#### Environment

- Platform version: 7.0, 7.1

#### Description of the bug or enhancement

1. Create a report using wizard
2. Create a new template for this report with Pivot table type
3. Try to set renderers for the table

**A.R.** Exception occurs
*7.0:*
```
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeSetter(MethodsCache.java:58)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:127)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:111)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:184)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:149)
	at com.haulmont.cuba.gui.components.data.value.DatasourceValueSource.setValue(DatasourceValueSource.java:133)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:278)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:271)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:88)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.componentValueChanged(WebAbstractField.java:222)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.lambda$attachListener$d776778f$1(WebAbstractField.java:206)
	at jdk.internal.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.haulmont.cuba.web.widgets.CubaListSelect.fireValueChangeEvent(CubaListSelect.java:89)
	at com.haulmont.cuba.web.widgets.CubaListSelect.fireValueChange(CubaListSelect.java:81)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:553)
	at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:745)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:450)
```

*7.1:*
```
java.lang.ClassCastException: class com.haulmont.reports.entity.pivottable.RendererType cannot be cast to class java.util.Set (com.haulmont.reports.entity.pivottable.RendererType is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @20b5f2ac; java.util.Set is in module java.base of loader 'bootstrap')
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:132)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:126)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:114)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:184)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValueEx(AbstractInstance.java:154)
	at com.haulmont.cuba.gui.components.data.value.DatasourceValueSource.setValue(DatasourceValueSource.java:133)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.setValueToSource(ValueBinder.java:278)
	at com.haulmont.cuba.gui.components.data.value.ValueBinder$ValueBindingImpl.componentValueChanged(ValueBinder.java:271)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:92)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.componentValueChanged(WebAbstractField.java:222)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.lambda$attachListener$d776778f$1(WebAbstractField.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:496)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1041)
	at com.haulmont.cuba.web.widgets.CubaListSelect.fireValueChangeEvent(CubaListSelect.java:124)
	at com.haulmont.cuba.web.widgets.CubaListSelect.fireValueChange(CubaListSelect.java:116)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:553)
	at com.vaadin.v7.ui.AbstractSelect.setValue(AbstractSelect.java:745)
	at com.vaadin.v7.ui.AbstractField.setValue(AbstractField.java:450)
	at com.vaadin.v7.ui.AbstractSelect.changeVariables(AbstractSelect.java:553)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:457)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:400)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Comment by natfirst** [comment]
1. Create a report using wizard
2. Create a new template for this report with Pivot table type
3. Open `Show Pivot Tables` screen
4. Select created report and try to run it
```
java.io.StreamCorruptedException: invalid stream header: 7B226361
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:877)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)
	at com.haulmont.cuba.core.sys.serialization.StandardSerialization$1.<init>(StandardSerialization.java:62)
	at com.haulmont.cuba.core.sys.serialization.StandardSerialization.deserialize(StandardSerialization.java:62)
	at com.haulmont.cuba.core.sys.serialization.StandardSerialization.deserialize(StandardSerialization.java:90)
	at com.haulmont.cuba.core.sys.serialization.SerializationSupport.deserialize(SerializationSupport.java:65)
	at com.haulmont.reports.gui.report.run.ShowPivotTableController.printReport(ShowPivotTableController.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:101)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
