### ISSUE TITLE
Error when running report within a report (IllegalStateException: Execution context already started)

### ISSUE THREAD

**Issue by PolinaSannikova** [cuba-platform/reports#228]
### Environment

- Platform version: 6.10.12

### Description of the bug or enhancement

Trying to create a PDF report with a groovy script custom template. The report should run several other PDF reports and collate them. However, an error appears, which seems to be related to running a report within a report.

- **Minimal reproducible example**

1.  Make sure there is a PDF report with code "TEST" in the system, which has input parameter of type Entity, with name "Entity". Please see attached example report (it users sec$User as input entity).
[Test.zip](https://github.com/cuba-platform/reports/files/3807952/Test.zip)

2. Create a groovy script, intended to be used in a custom template report, which, for a list of input entities, would run report "TEST" for each of them and merge these reports in one big PDF. Example script attached:
[TestMergedGroovy.zip](https://github.com/cuba-platform/reports/files/3807972/TestMergedGroovy.zip)

3. Create a report which has input parameter "Entities" - list of the same entities as in the report created in step 1. This report would use the script created in step 2. Example report attached:
[Test Merged.zip](https://github.com/cuba-platform/reports/files/3807997/Test.Merged.zip)

4. Run the report from step 3.

- **Expected behavior**
Report runs (I am actually not sure if it runs because I cannot get past the error that this ticket is related to)
- **Actual behavior**
Error:
```
java.lang.IllegalStateException: Execution context already started
	at com.haulmont.cuba.core.app.execution.ExecutionsImpl.startExecution(ExecutionsImpl.java:75)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:312)
	at com.haulmont.taxi.core.app.reports.TaxiReportingBean.createReportExecutionAndReportDocument(TaxiReportingBean.java:80)
	at com.haulmont.taxi.core.app.reports.TaxiReportingBean.createReportDocument(TaxiReportingBean.java:54)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:304)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:198)
	at com.haulmont.reports.ReportingApi$createReport.call(Unknown Source)
	at TestMerged.run(TestMerged.groovy:21)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:599)
	at com.haulmont.cuba.core.sys.AbstractScripting.runGroovyScript(AbstractScripting.java:238)
	at com.haulmont.cuba.core.sys.AbstractScripting.runGroovyScript(AbstractScripting.java:269)
	at com.haulmont.reports.libintegration.CustomFormatter.generateReportWithScript(CustomFormatter.java:112)
	at com.haulmont.reports.libintegration.CustomFormatter.createDocument(CustomFormatter.java:78)
	at com.haulmont.reports.libintegration.CustomFormatter.createReport(CustomFormatter.java:69)
	at com.haulmont.yarg.reporting.Reporting.generateReport(Reporting.java:125)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:100)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:83)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:335)
	at com.haulmont.taxi.core.app.reports.TaxiReportingBean.createReportExecutionAndReportDocument(TaxiReportingBean.java:80)
	at com.haulmont.taxi.core.app.reports.TaxiReportingBean.createReportDocument(TaxiReportingBean.java:54)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:304)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:198)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35)
	at sun.reflect.GeneratedMethodAccessor3703.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:116)
	at sun.reflect.GeneratedMethodAccessor846.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy341.createReport(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor3703.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy879.createReport(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor4673.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:212)
	at com.haulmont.cuba.core.sys.remoting.CubaRemoteInvocationExecutor.invoke(CubaRemoteInvocationExecutor.java:110)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
	at com.haulmont.taxi.core.common.remoting.TaxiHttpServiceExporter.handleRequest(TaxiHttpServiceExporter.java:58)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at com.haulmont.cuba.core.sys.remoting.RemotingServlet.doService(RemotingServlet.java:124)
	at com.haulmont.taxi.core.sys.remoting.TaxiRemotingServlet.doService(TaxiRemotingServlet.java:27)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by alexbudarov** [comment]
@PolinaSannikova this problem was solved in the PdfReportMerger Sherlock class, please look into its implementation.

(For everyone):
It launches report in another thread pool executor:
```
ThreadPoolTaskExecutor reportThreadExecutor = AppBeans.get("reportTaskExecutor")
Authentication authentication = AppBeans.get(Authentication.NAME);
reportThreadExecutor.submit(() -> {
    authentication.begin("ReportScheduling");
    try {
        Map<String, Object> reportParams = new HashMap<>(params);
        reportParams.put(entityName, entity);
        return reporting.createReport(singleReport, reportParams).getContent();
    } finally {
        authentication.end();
    }
})
// ...
byte[] result = r.get()
```
