### ISSUE TITLE
Implement ability to use "Pivot" table in the Reporting addon (as a chart)

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#50]
Implement ability to use "Pivot" table in the Reporting addon (as a chart)

The pivot table is enabled then Charts add-on is used in the CUBA application.

Pivot table configuration includes: 

- Band name - show data only from the selected band
- Is editable -  if true, the elements for manipulation with data will be displayed in the UI, otherwise, only the data will be displayed.
- Renderers tab: 
  - Renderers - the collection of rendering functions that should be displayed in the list of available renderers in the UI.
  - Default attribute enables setting one of the predefined renderers. The selected renderer will be used as default when the component is loaded.
- Aggregation tab:
  - Defines the collection of aggregators that should be displayed in the dropdown list of available aggregators in the UI
  - Default attribute enables setting one of the predefined aggregation functions. The selected function will be used as default when the component is loaded.
  - Aggregation custom function - contains JavaScript code of an aggregation function.
- Custom options tab:
  - Filter function - JavaScript function that will be used for filtration.
  - Sorters function - JavaScript function that will be used for rows and columns captions sorting
  - Custom C3 options: Width, Height - sizes for charts
  - Custom heatmap properties: Color scale function - JavaScript function that will be used for cell colours.
- Properties tab
  - Columns the list of attributes to be used as table columns.
  - Rows the list of attributes to be used as table rows .
  - Aggregations the list of attributes to be used as aggregated value.
  - Custom function for property - JavaScript function that generates this attribute from the existing ones

Also see https://doc.cuba-platform.com/charts-6.8/pivotTable.html

---
Original issue: https://youtrack.haulmont.com/issue/PL-10052

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: [8d443da4](https://git.haulmont.com/platform/reports/commit/8d443da454edf8942cc68772d2bda46deeee588f) in **release_6_9**

 `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by andreysubbotin** [comment]
Git changesets by `subbotin`: [9c8139bd](https://git.haulmont.com/platform/reports/commit/9c8139bd78cc6b027c90260679a8139e57f2dae2) in **release_6_9**

 `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by andreysubbotin** [comment]
Git changesets by `subbotin`: [e1ca707e](https://git.haulmont.com/platform/reports/commit/e1ca707eba8ea20037d5a943552c98e7b495a623) in **master**

 `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by andreysubbotin** [comment]
Git changesets by `subbotin`: [c1d85e88](https://git.haulmont.com/platform/reports/commit/c1d85e88a5954a522b6de8bbd91b09bb6a45b27f) in **master**

 `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[a9005735](https://git.haulmont.com/platform/reports/commit/a900573535ff61391230207f7139ff7feb1c5e95) in **master** - `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[6c5f4093](https://git.haulmont.com/platform/reports/commit/6c5f4093d5b27fb86fb6109a987423b7d6294c6b) in **release_6_9** - `Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50
`

**Comment by oshiryaeva** [comment]
№1
![50_pivot_in_reporting__window_caption](https://user-images.githubusercontent.com/11287637/39629056-fd69c43e-4fbb-11e8-84f4-5f66dbb13cf6.png)
The window caption is missing: stub instead of "Edit aggregation option"

**Comment by oshiryaeva** [comment]
№2
![50_pivot_in_reporting__window_caption](https://user-images.githubusercontent.com/11287637/39629204-6e02ec48-4fbc-11e8-93d8-870c91ff8265.png)
![50_pivot_in_reporting__context_help_example](https://user-images.githubusercontent.com/11287637/39629209-722b009e-4fbc-11e8-81bf-7cdfacdb6233.png)
Usability issue: add context help with some examples

**Comment by oshiryaeva** [comment]
№3
![50_pivot_in_reporting__font_size issue](https://user-images.githubusercontent.com/11287637/39629288-b493f5da-4fbc-11e8-9f3b-5af124805752.png)
Font size is obviously smaller (in all browsers)

**Comment by oshiryaeva** [comment]
№4
![50_pivot_in_reporting__editable_unable_to_close](https://user-images.githubusercontent.com/11287637/39629400-21b55bfe-4fbd-11e8-8253-680a2a85a9d9.png)
If editable=true, the dialog windows of UI components exceed the editor's dialog size and cannot be closed

**Comment by oshiryaeva** [comment]
№5
![50_pivot_in_reporting__autofill](https://user-images.githubusercontent.com/11287637/39629474-65972172-4fbd-11e8-9d5d-9d212df7a592.png)
When the Name field is filled for the first time, it is auto-filled in the Caption field. When it is edited, nothing happens. Also, the caption should by default start with a capital, just to be more CUBA-like.

**Comment by oshiryaeva** [comment]
№6
![50_pivot_in_reporting__wizard](https://user-images.githubusercontent.com/11287637/39629565-b347543c-4fbd-11e8-88d5-91af7bdcf3c8.png)
Pivot template is missing in the report wizard

**Comment by oshiryaeva** [comment]
№7
![50_pivot_in_reporting__usability_type](https://user-images.githubusercontent.com/11287637/39629615-d9e16a06-4fbd-11e8-86cc-2dac9bf17154.png)
Usability: better do this field editable with 3 possible values: Column, Row, Aggregation, in order to facilitate the properties transfer from one type to another.

**Comment by oshiryaeva** [comment]
№8
![50_pivot_in_reporting__mode-duplicates](https://user-images.githubusercontent.com/11287637/39629751-470715ae-4fbe-11e8-972a-a2d8eacab2d5.png)
![50_pivot_in_reporting__mode-duplicates2](https://user-images.githubusercontent.com/11287637/39629754-492a61f6-4fbe-11e8-835d-9e6f2c8715f3.png)
Now the editor allows adding unlimited numbers of identical aggregation options. It would be better to enable saving only the options that have some differences either in caption and/or in function.

**Comment by oshiryaeva** [comment]
№9
Duplicate keys
The editor allows saving properties with duplicate keys, for example, "totalBill" in Row, Column and Aggregation. The following exception is thrown, but the template is however saved:
 `java.lang.IllegalStateException: Duplicate key totalBill
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.haulmont.charts.web.ui.PivotTableController.createProperties(PivotTableController.java:141)
	at com.haulmont.charts.web.ui.PivotTableController.init(PivotTableController.java:55)
	at com.haulmont.cuba.gui.xml.layout.loaders.FrameLoader$FrameLoaderInitTask.execute(FrameLoader.java:271)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext$InitTaskExecutor.run(ComponentLoaderContext.java:266)
	at com.haulmont.cuba.gui.xml.layout.loaders.ComponentLoaderContext.executeInitTasks(ComponentLoaderContext.java:160)
	at com.haulmont.cuba.gui.WindowManager.openFrame(WindowManager.java:1009)
	at com.haulmont.cuba.gui.WindowManager.openFrame(WindowManager.java:959)
	at com.haulmont.cuba.web.gui.components.WebFrame.openFrame(WebFrame.java:412)
	at com.haulmont.cuba.gui.components.AbstractFrame.openFrame(AbstractFrame.java:564)
	at com.haulmont.reports.gui.template.edit.PivotTableEditFrame.initPreviewContent(PivotTableEditFrame.java:131)
	at com.haulmont.reports.gui.template.edit.DescriptionEditFrame.showPreview(DescriptionEditFrame.java:45)
	at com.haulmont.reports.gui.template.edit.PivotTableEditFrame.lambda$init$0(PivotTableEditFrame.java:81)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource$ItemListener.propertyChanged(AbstractDatasource.java:307)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:51)
	at com.haulmont.reports.entity.pivottable.PivotTableDescription.setSortersFunction(PivotTableDescription.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeSetter(MethodsCache.java:59)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:133)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:119)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:117)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:188)
	at com.haulmont.cuba.web.gui.data.PropertyWrapper.setValue(PropertyWrapper.java:97)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:564)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:494)
	at org.vaadin.aceeditor.AceEditor.diffFromClient(AceEditor.java:667)
	at org.vaadin.aceeditor.AceEditor.clientChanged(AceEditor.java:621)
	at org.vaadin.aceeditor.AceEditor$1.changed(AceEditor.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:444)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:409)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:306)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:197)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`
Moreover, after saving such template it cannot be then edited:
![50_pivot_in_reporting__duplicate-key](https://user-images.githubusercontent.com/11287637/39630002-07325244-4fbf-11e8-8245-c3d4b4ebb991.png)
Solution: validate duplicate keys before saving and show an alert instead of throwing an exception.

**Comment by oshiryaeva** [comment]
№10
![50_pivot_in_reporting__no-data](https://user-images.githubusercontent.com/11287637/39630067-44c91d40-4fbf-11e8-8052-77c52adab59b.png)
If no data is received from the band, then an alert should be shown to the user.

**Comment by oshiryaeva** [comment]
№13
![50_pivot_in_reporting__properties](https://user-images.githubusercontent.com/11287637/39630343-1c1d84c0-4fc0-11e8-8f56-5b088efd2329.png)
Usability: show available variables from the selected band

**Comment by oshiryaeva** [comment]
№14
![50_pivot_in_reporting__copy_template](https://user-images.githubusercontent.com/11287637/39630407-478b559c-4fc0-11e8-8350-29d938a53ceb.png)
Implement the ability to copy the templates

**Comment by oshiryaeva** [comment]
№15
![50_pivot_in_reporting__save](https://user-images.githubusercontent.com/11287637/39630469-6d092c4a-4fc0-11e8-98be-ad925d9e6bae.png)
Usability: implement the ability to save/download the report results, both from "Show Pivot tables" screen and the report editor

**Comment by oshiryaeva** [comment]
№16

> Aggregation custom function - contains JavaScript code of an aggregation function.

Report is executed silently, neither a result nor an error are shown to the user.

In app.log:
```
2018-05-04 16:07:06.979 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=report$Report, id=010de2b0-b51d-223f-cc47-7c48e022d791, view=com.haulmont.reports.entity.Report/report.edit
2018-05-04 16:07:07.029 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.execution.ExecutionsImpl - Start execution context: group=Reporting, key=010de2b0-b51d-223f-cc47-7c48e022d791
2018-05-04 16:07:07.029 INFO  [http-nio-8080-exec-9/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - Started report [Report for entity "Tip Info"] with parameters [
entities:[com.company.sample.entity.TipInfo-21e8600d-26e0-ab22-16d8-c79d7f7ba241 [detached], com.company.sample.entity.TipInfo-5690f37d-2cb3-e63c-83ec-061883a5acc8 [detached], com.company.sample.entity.TipInfo-206a4807-40f6-3fbb-0bf8-6e2d90a823b1 [detached], com.company.sample.entity.TipInfo-56269eb2-7df7-cc78-1145-293080cae148 [detached]]]
2018-05-04 16:07:07.030 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=21e8600d-26e0-ab22-16d8-c79d7f7ba241, view=com.company.sample.entity.TipInfo/
2018-05-04 16:07:07.036 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=5690f37d-2cb3-e63c-83ec-061883a5acc8, view=com.company.sample.entity.TipInfo/
2018-05-04 16:07:07.041 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=206a4807-40f6-3fbb-0bf8-6e2d90a823b1, view=com.company.sample.entity.TipInfo/
2018-05-04 16:07:07.046 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=56269eb2-7df7-cc78-1145-293080cae148, view=com.company.sample.entity.TipInfo/
2018-05-04 16:07:07.051 INFO  [http-nio-8080-exec-9/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - Finished report [Report for entity "Tip Info"] with parameters [
entities:[com.company.sample.entity.TipInfo-21e8600d-26e0-ab22-16d8-c79d7f7ba241 [detached], com.company.sample.entity.TipInfo-5690f37d-2cb3-e63c-83ec-061883a5acc8 [detached], com.company.sample.entity.TipInfo-206a4807-40f6-3fbb-0bf8-6e2d90a823b1 [detached], com.company.sample.entity.TipInfo-56269eb2-7df7-cc78-1145-293080cae148 [detached]]]
2018-05-04 16:07:07.052 DEBUG [http-nio-8080-exec-9/app-core/admin] com.haulmont.cuba.core.app.execution.ExecutionsImpl - End execution context: group=Reporting, key=010de2b0-b51d-223f-cc47-7c48e022d791
```

**Comment by oshiryaeva** [comment]
№17

> Custom function for property - JavaScript function that generates this attribute from the existing ones

The same as №16: runs silently, nothing happens, no report shown

```
com.haulmont.cuba.core.app.execution.ExecutionsImpl - Start execution context: group=Reporting, key=010de2b0-b51d-223f-cc47-7c48e022d791
2018-05-04 16:47:50.207 INFO  [http-nio-8080-exec-6/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - Started report [Report for entity "Tip Info"] with parameters [
entities:[com.company.sample.entity.TipInfo-c8314731-20d3-fcaf-af49-e0871afa85c2 [detached], com.company.sample.entity.TipInfo-1ad173c6-670c-d3ed-0956-9f962cf692ae [detached]]]
2018-05-04 16:47:50.212 DEBUG [http-nio-8080-exec-6/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=c8314731-20d3-fcaf-af49-e0871afa85c2, view=com.company.sample.entity.TipInfo/
2018-05-04 16:47:50.221 DEBUG [http-nio-8080-exec-6/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=sample$TipInfo, id=1ad173c6-670c-d3ed-0956-9f962cf692ae, view=com.company.sample.entity.TipInfo/
2018-05-04 16:47:50.270 INFO  [http-nio-8080-exec-6/app-core/admin] com.haulmont.reports.libintegration.CubaReporting - Finished report [Report for entity "Tip Info"] with parameters [
entities:[com.company.sample.entity.TipInfo-c8314731-20d3-fcaf-af49-e0871afa85c2 [detached], com.company.sample.entity.TipInfo-1ad173c6-670c-d3ed-0956-9f962cf692ae [detached]]]
2018-05-04 16:47:50.272 DEBUG [http-nio-8080-exec-6/app-core/admin] com.haulmont.cuba.core.app.execution.ExecutionsImpl - End execution context: group=Reporting, key=010de2b0-b51d-223f-cc47-7c48e022d791
```

**Comment by oshiryaeva** [comment]
№18
rename **Detached** properties to **Derived** properties

**Comment by oshiryaeva** [comment]
№19

> IllegalArgumentException: Property 'createTs' not found in sys$KeyValueEntity 

if createTs is used in the report

```
java.lang.IllegalArgumentException: Property 'createTs' not found in sys$KeyValueEntity
	at com.haulmont.chile.core.model.impl.MetaClassImpl.getPropertyNN(MetaClassImpl.java:107)
	at com.haulmont.charts.gui.pivottable.model.gson.PivotDataItemsSerializer.addProperty(PivotDataItemsSerializer.java:70)
	at com.haulmont.charts.gui.pivottable.model.gson.PivotDataItemsSerializer.serialize(PivotDataItemsSerializer.java:46)
	at com.haulmont.charts.gui.pivottable.model.gson.PivotDataProviderSerializer.serialize(PivotDataProviderSerializer.java:20)
	at com.haulmont.charts.gui.pivottable.model.PivotTableModel.dataToString(PivotTableModel.java:591)
	at com.haulmont.charts.web.toolkit.ui.pivottable.CubaPivotTable.beforeClientResponse(CubaPivotTable.java:146)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:100)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:306)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:197)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
WTR:
- sample-workshop
- report band:
```
select
e.amount as "amount",
e.status as "status",
e.hoursSpent as "hoursSpent",
client.name as "client.name",
e.createTs as "createTs",
mechanic_user.name as "mechanic.user.name"
from workshop$Order e  
left join e.client client 
left join e.mechanic.user mechanic_user 
 where (e.createTs >= ${createTs1} and e.createTs <= ${createTs2})
```
or the report attached
[Report for entity _Order.zip](https://github.com/cuba-platform/reports/files/1983580/Report.for.entity._Order.zip)

**Comment by andreysubbotin** [comment]
https://git.haulmont.com/platform/reports/commit/3e1d4d76fa9bca5ec8e95bee3abd05accf035693
https://git.haulmont.com/platform/charts/commit/1282b4554434138055c654a76ac3831681a44a88

**Comment by oshiryaeva** [comment]
![image](https://user-images.githubusercontent.com/11287637/40175890-acdd3062-59ea-11e8-8a25-ced902afb1fc.png)
![image](https://user-images.githubusercontent.com/11287637/40175895-b090577a-59ea-11e8-9098-b0262d95af4d.png)

Set the same width for Mode, Caption and Type fields as for the Custom function field

**Comment by oshiryaeva** [comment]
![image](https://user-images.githubusercontent.com/11287637/40176625-1634c9e2-59ed-11e8-9769-4695c29f4f53.png)
№21 Small regression: set larger width to fit "Default aggregation" inputPrompt width

**Comment by oshiryaeva** [comment]
№16, 17: still doesn't work
![derived](https://user-images.githubusercontent.com/11287637/40180736-8fc0972c-59f8-11e8-8ef3-aa610cc37dec.gif)

**Comment by oshiryaeva** [comment]
Summary:

№1, 2, 5, 7, 8, 9, 11, 18, 19 - fixed
№3 regression, see №21
№12 not fixed, see №22
№16, 17 - not fixed
№4, 6, 10, 13, 14, 15 moved to separate tickets
New issues: 
№20, 21

**Comment by andreysubbotin** [comment]
https://git.haulmont.com/platform/reports/commit/c7df6f615b7fc2104b42bfa46edfb9ebac47e8fc

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[f62aa46d](https://git.haulmont.com/platform/reports/commit/f62aa46d0fd422ff1a2d53d9b3612924c5a4e019) in **release_6_9** - Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50

Bugfix: 20,21,22

**Comment by oshiryaeva** [comment]
№23 Support datasets: Entity and List of Entities
№24 Support nested bands

**Comment by andreysubbotin** [comment]
@oshiryaeva nested bands can't be supported by pivot table

**Comment by oshiryaeva** [comment]
№25 
Provide support of periods in properties' names
```
select
e.amount as "amount",
e.status as "status",
e.hoursSpent as "hoursSpent",
client.name as "client",
e.createTs as "createTs.test",
mechanic_user.name as "mechanic"
from workshop$Order e  
left join e.client client 
left join e.mechanic.user mechanic_user 
 where (e.createTs >= ${createTs1} and e.createTs <= ${createTs2})
```

as "**client.name**" - doesn't work
as "**client**" - works
as "**createTs.test**" (local attribute!) - doesn't work
as "**createTs**" - works

![image](https://user-images.githubusercontent.com/11287637/40306484-e7a43e02-5d0f-11e8-991a-c5e41de9e9af.png)

**Comment by oshiryaeva** [comment]
№26
Replace "по-умолчанию" by "по умолчанию" everywhere in Russian messages, no hyphen is needed here.

**Comment by andreysubbotin** [comment]
@oshiryaeva What is the problem with the list of entities (№23)? I

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[c618cdab](https://git.haulmont.com/platform/reports/commit/c618cdab676c0d5733bd158bc31cc7cfcd836648) in **release_6_9** - Implement ability to use "Pivot" table in the Reporting addon (as a chart) #50

26 resolved

**Comment by oshiryaeva** [comment]
@andreysubbotin Dataset types Entity and List of Entities work correctly.
Enum attributes are displayed correctly in Entity and List of Entities. In case of SQL/JPQL only the int id is displayed.

**Comment by andreysubbotin** [comment]
Issue 25 is a known problem. JPQL, SQL, Groovy bands doesn't support dots in the property names.
