### ISSUE TITLE
IllegalArgumentException on attempt to print table report by view with to many collection attribute

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/reports#51]
1) Create a couple of entities: Master and Detail
2) Link  them  with ''one_to_many'' or ''many_to_many'' association
3) For Master create a *view* which includes the link (to details) attribute 
4) (Using wizard) Create a new report for "list of entities"
5) Add a new band with the "List of entities" type
6) Enable "Use existing view " select the *view above*
7) Create a new template with the table output type make it default 

8) try to print the report see the attached screenshot)

AR: Exception

```
2017-11-23 16:19:34.712 ERROR [http-nio-8080-exec-7/app/admin] com.haulmont.cuba.web.log.AppLog - Exception in com.haulmont.cuba.web.toolkit.ui.CubaButton: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:160) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:444) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:409) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1436) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) [vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:301) [cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:192) [cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:na]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.21]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.21]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.21]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.21]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.21]
at com.haulmont.cuba.web.sys.CubaHttpFilter.handleNotFiltered(CubaHttpFilter.java:108) [cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:95) [cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.21]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.21]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.21]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.21]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [catalina.jar:8.5.21]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.21]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.21]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.21]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.21]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.21]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-coyote.jar:8.5.21]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.21]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:8.5.21]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-coyote.jar:8.5.21]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.21]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
... 37 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in com.haulmont.cuba.web.gui.components.WebButton$$Lambda$104/841028923 failed.
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:530) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.vaadin.ui.Button.fireClick(Button.java:377) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
at com.haulmont.cuba.web.toolkit.ui.CubaButton.fireClick(CubaButton.java:54) ~[cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.vaadin.ui.Button$1.click(Button.java:54) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
... 41 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:94) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:44) ~[cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:36) ~[cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) ~[vaadin-server-7.7.10.cuba.9.jar:7.7.10.cuba.9]
... 47 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:92) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
... 53 common frames omitted
Caused by: java.lang.IllegalArgumentException: A datatype for class org.eclipse.persistence.internal.indirection.jdk8.IndirectList is not found
at com.haulmont.cuba.core.sys.DatatypeRegistryImpl.getNN(DatatypeRegistryImpl.java:74) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.chile.core.datatypes.Datatypes.getNN(Datatypes.java:79) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.core.app.keyvalue.KeyValueMetaProperty.<init>(KeyValueMetaProperty.java:69) ~[cuba-global-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.data.impl.ValueDatasourceDelegate.addProperty(ValueDatasourceDelegate.java:69) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.data.impl.ValueGroupDatasourceImpl.addProperty(ValueGroupDatasourceImpl.java:69) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.report.run.ShowReportTable.lambda$createDataSource$2(ShowReportTable.java:174) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_151]
at com.haulmont.reports.gui.report.run.ShowReportTable.createDataSource(ShowReportTable.java:174) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.report.run.ShowReportTable.lambda$drawTables$1(ShowReportTable.java:157) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_151]
at com.haulmont.reports.gui.report.run.ShowReportTable.drawTables(ShowReportTable.java:155) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.report.run.ShowReportTable.init(ShowReportTable.java:99) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.WindowManager.init(WindowManager.java:1238) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.WindowManager.initWrapperFrame(WindowManager.java:1227) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.WindowManager.createWindow(WindowManager.java:582) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.WindowManager.openWindow(WindowManager.java:751) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.WebWindowManager.openWindow(WebWindowManager.java:147) ~[cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.components.WindowDelegate.openWindow(WindowDelegate.java:233) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.web.gui.WebWindow.openWindow(WebWindow.java:458) ~[cuba-web-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.components.AbstractFrame.openWindow(AbstractFrame.java:477) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.cuba.gui.components.AbstractFrame.openWindow(AbstractFrame.java:44) ~[cuba-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.ReportGuiManager.showReportResult(ReportGuiManager.java:303) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.ReportGuiManager.showReportResult(ReportGuiManager.java:277) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.ReportGuiManager.printReportSync(ReportGuiManager.java:237) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:206) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
at com.haulmont.reports.gui.report.run.InputParametersWindow.printReport(InputParametersWindow.java:163) ~[reports-gui-6.7-SNAPSHOT.jar:6.7-SNAPSHOT]
... 58 common frames omitted
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-10073

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[4fa4c23b](https://git.haulmont.com/platform/reports/commit/4fa4c23b29e6bdbcbdb6f5fc1503251743e7c265) in **release_6_10** - IllegalArgumentException on attempt to print table report by view with to many collection attribute #51

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[6999bfd1](https://git.haulmont.com/platform/reports/commit/6999bfd1d57ed004cc00bc92c9e985ff166b7aa3) in **master** - IllegalArgumentException on attempt to print table report by view with to many collection attribute #51
