### ISSUE TITLE
NoSuchMethodError occurred when XLS report running

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/reports#77]
- Platform version: 6.9-snapshot
- Library project

1. Open the Library project
2. Update the platform version 
3. Add reports addon
4. Run the application
5. Import Reports.zip from the project root directory.
6. Run the ` Book availability in department` report

**A.R.** Exception will appear

```
java.lang.NoSuchMethodError: org.apache.poi.ss.util.AreaReference.<init>(Ljava/lang/String;)V
	at com.haulmont.yarg.formatters.impl.XLSFormatter.initMergeRegions(XLSFormatter.java:478)
	at com.haulmont.yarg.formatters.impl.XLSFormatter.initWorkbook(XLSFormatter.java:135)
	at com.haulmont.yarg.formatters.impl.XLSFormatter.renderDocument(XLSFormatter.java:113)
	at com.haulmont.yarg.reporting.Reporting.generateReport(Reporting.java:133)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:100)
	at com.haulmont.yarg.reporting.Reporting.runReport(Reporting.java:83)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:315)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:284)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:202)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy264.createReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy60.createReport(Unknown Source)
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:267)
	at com.haulmont.reports.gui.ReportGuiManager.printReportSync(ReportGuiManager.java:236)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:207)
	at com.haulmont.reports.gui.report.run.InputParametersWindow.printReport(InputParametersWindow.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:92)
	at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:45)
	at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:37)
	at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.haulmont.cuba.web.toolkit.ui.CubaButton.fireClick(CubaButton.java:54)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
```

**Comment by andreysubbotin** [comment]
Dependent issue: https://github.com/cuba-platform/yarg/issues/74

**Comment by andreysubbotin** [comment]
Caused by: https://youtrack.haulmont.com/issue/PL-10642

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[a2b9ebcd](https://git.haulmont.com/platform/reports/commit/a2b9ebcdfa648d3f29c93a0f4a0277d4bc431768) in **master** - NoSuchMethodError occurred when XLS report running #77

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[03a416dc](https://git.haulmont.com/platform/reports/commit/03a416dcd72b1697dd11229aaf57c41b22c93205) in **release_6_9** - NoSuchMethodError occurred when XLS report running #77
