### ISSUE TITLE
TablePrintFormAction.printAll method should not use paging parameters 

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/reports#88]
### Environment

- Platform version: 6.9.1

### Description of the bug or enhancement

Now it uses `firstResult` and `maxResults` obtained from `datasource.getCompiledLoadContext()` which luckily doesn't provide them.

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[a118a343](https://git.haulmont.com/platform/reports/commit/a118a3432fa6c62cc3007247ef0b7eb04eaa0473) in **release_6_10** - TablePrintFormAction.printAll method should not use paging parameters #88

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[dd1e8666](https://git.haulmont.com/platform/reports/commit/dd1e8666f3b69209c22d27614797fca4b22c1b74) in **master** - TablePrintFormAction.printAll method should not use paging parameters #88

**Comment by andreysubbotin** [comment]
For QA: "Print all" should print entities without binding to the current page and the max results on the page

**Comment by natfirst** [comment]
1. Add a report button with the TablePrintFormAction to the User browser  as it described here https://doc.cuba-platform.com/reporting-6.9/run_actions.html
2. Create a lot of users
3. Create a report with the List of entities type for the User entity, add it to the User browser screen
4. Try to run the report from the User browser screen
```
java.lang.NullPointerException
	at com.haulmont.reports.PrototypesLoader.loadData(PrototypesLoader.java:67)
	at com.haulmont.reports.ReportingBean.loadDataForParameterPrototype(ReportingBean.java:354)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:304)
	at com.haulmont.reports.ReportingBean.createReportDocument(ReportingBean.java:284)
	at com.haulmont.reports.ReportingBean.createReport(ReportingBean.java:188)
	at com.haulmont.reports.ReportServiceBean.createReport(ReportServiceBean.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy264.createReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy60.createReport(Unknown Source)
	at com.haulmont.reports.gui.ReportGuiManager.getReportResult(ReportGuiManager.java:265)
	at com.haulmont.reports.gui.ReportGuiManager.printReportSync(ReportGuiManager.java:236)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:207)
	at com.haulmont.reports.gui.ReportGuiManager.printReport(ReportGuiManager.java:186)
	at com.haulmont.reports.gui.ReportGuiManager.runReport(ReportGuiManager.java:138)
	at com.haulmont.reports.gui.actions.AbstractPrintFormAction.openRunReportScreen(AbstractPrintFormAction.java:73)
	at com.haulmont.reports.gui.actions.AbstractPrintFormAction.openRunReportScreen(AbstractPrintFormAction.java:44)
	at com.haulmont.reports.gui.actions.TablePrintFormAction.printAll(TablePrintFormAction.java:140)
	at com.haulmont.reports.gui.actions.TablePrintFormAction$3.actionPerform(TablePrintFormAction.java:105)
	at com.haulmont.cuba.web.WebWindowManager.lambda$showOptionDialog$297bf31$1(WebWindowManager.java:1410)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[0d403e48](https://git.haulmont.com/platform/reports/commit/0d403e4874b8a6e9f18ddf902a2cf87dcfd77796) in **master** - TablePrintFormAction.printAll method should not use paging parameters #88

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[a3b3598a](https://git.haulmont.com/platform/reports/commit/a3b3598a9e60fe988cb34e3f638fac90d5562157) in **release_6_10** - TablePrintFormAction.printAll method should not use paging parameters #88
