### ISSUE TITLE
Exception when select output type PivotTable or Chart for template

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/reports#94]
### Environment
- Platform version: 6.9.4

### How to reproduce
1. Create simple report for User entity with several properties (using wizard)
2. Try to edit report template
3. Select in template editor "output type" - `Chart`  

**AR** Stacktrace:
```
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:896)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.haulmont.reports.entity.charts.AbstractChartDescription.fromJsonString(AbstractChartDescription.java:34)
	at com.haulmont.reports.entity.ReportTemplate.getChartDescription(ReportTemplate.java:211)
	at com.haulmont.reports.gui.template.edit.ChartEditFrame.setItem(ChartEditFrame.java:84)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.setupVisibilityDescriptionEdit(TemplateEditor.java:195)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.setupVisibility(TemplateEditor.java:184)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.lambda$postInit$0(TemplateEditor.java:135)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource$ItemListener.propertyChanged(AbstractDatasource.java:307)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:51)
	at com.haulmont.reports.entity.ReportTemplate.setReportOutputType(ReportTemplate.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeSetter(MethodsCache.java:59)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:133)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:119)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:117)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:188)
	at com.haulmont.cuba.web.gui.data.PropertyWrapper.setValue(PropertyWrapper.java:97)
	at com.haulmont.cuba.web.gui.components.WebLookupField$LookupPropertyAdapter.setValue(WebLookupField.java:878)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:564)
	at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:738)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:494)
	at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:750)
	at com.haulmont.cuba.web.toolkit.ui.CubaComboBox.changeVariables(CubaComboBox.java:167)
```
4. Try to select "output type" - `Pivot table`  

**AR** Stacktrace:
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.haulmont.reports.entity.pivottable.PivotTableDescription.fromJsonString(PivotTableDescription.java:211)
	at com.haulmont.reports.entity.ReportTemplate.getPivotTableDescription(ReportTemplate.java:225)
	at com.haulmont.reports.gui.template.edit.PivotTableEditFrame.setItem(PivotTableEditFrame.java:94)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.setupVisibilityDescriptionEdit(TemplateEditor.java:195)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.setupVisibility(TemplateEditor.java:184)
	at com.haulmont.reports.gui.template.edit.TemplateEditor.lambda$postInit$0(TemplateEditor.java:135)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.gui.data.impl.AbstractDatasource$ItemListener.propertyChanged(AbstractDatasource.java:307)
	at com.haulmont.chile.core.model.impl.AbstractInstance.propertyChanged(AbstractInstance.java:51)
	at com.haulmont.reports.entity.ReportTemplate.setReportOutputType(ReportTemplate.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.chile.core.model.utils.MethodsCache.invokeSetter(MethodsCache.java:59)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:133)
	at com.haulmont.cuba.core.entity.BaseGenericIdEntity.setValue(BaseGenericIdEntity.java:119)
	at com.haulmont.chile.core.model.impl.AbstractInstance.setValue(AbstractInstance.java:117)
	at com.haulmont.chile.core.model.utils.InstanceUtils.setValueEx(InstanceUtils.java:188)
	at com.haulmont.cuba.web.gui.data.PropertyWrapper.setValue(PropertyWrapper.java:97)
	at com.haulmont.cuba.web.gui.components.WebLookupField$LookupPropertyAdapter.setValue(WebLookupField.java:878)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:564)
	at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:738)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:494)
	at com.vaadin.ui.ComboBox.changeVariables(ComboBox.java:750)
	at com.haulmont.cuba.web.toolkit.ui.CubaComboBox.changeVariables(CubaComboBox.java:167)
```

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[445926c1](https://git.haulmont.com/platform/reports/commit/445926c149a7d4da1f21b5cf409d2bfbac858319) in **release_6_9** - Exception when select output type PivotTable or Chart for template #94

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[57e83197](https://git.haulmont.com/platform/reports/commit/57e83197bff5257edf04dc27eab82afbc576edb8) in **master** - Exception when select output type PivotTable or Chart for template #94
